add app components with events and setters
stripe/connect-js pull request #137
Opened 2024-07-10 23:52 UTC by chaves-stripe

We don't currently have apps on furever, so I wasn't able to test there. I used yalc to point to these local changes from sample platform to observe everything working as expected. 

<img width="993" alt="Screenshot 2024-07-10 at 4 51 29 PM" src="https://github.com/stripe/connect-js/assets/47334649/310316c2-5ed2-4d93-b048-d662811ae3c3">

<img width="1131" alt="Screenshot 2024-07-10 at 4 51 35 PM" src="https://github.com/stripe/connect-js/assets/47334649/27e1e366-27a7-4255-8b7c-e30fbf74a6f4">

2024-07-11 16:52 UTC, hliana-stripe commented
@chaves how does your sample_platform test setup look like? Does this include you setting the `setOnAppInstallStateFetched` and `setOnAppInstallStateChanged` callbacks on the component? The sample_platform screenshot shows you setting the HTML parameters, which are different from the setters you are adding.

2024-07-11 20:01 UTC, jorgea-stripe requested changes
Spotted a repeated item on the union type, otherwise looks good!

2024-07-11 20:01 UTC, jorgea-stripe commented on types/shared.d.ts
> +  | "app-install"
Both of these are already on the list below

2024-07-15 22:46 UTC, chaves-stripe commented
> @chaves how does your sample_platform test setup look like? Does this include you setting the `setOnAppInstallStateFetched` and `setOnAppInstallStateChanged` callbacks on the component? The sample_platform screenshot shows you setting the HTML parameters, which are different from the setters you are adding.
> 
> (also curious because we should be only passing in the "detail" portion of the event, which isn't reflected in the console log)

hi @hliana-stripe . Apologies for being less familiar with how i can adjust the setup, but my understanding with sample_platform is it takes your configuration and sets the callbacks automatically? so just pulling from here https://livegrep.corp.stripe.com/view/stripe-internal/pay-server/frontend/connect/submerchant-surfaces/src/connect/ConnectJSInterface/ConnectElementDefinitions/app-install.ts#L43. Should I be doing anything differently here?

2024-07-15 22:58 UTC, chaves-stripe commented
r? @jorgea-stripe

2024-07-15 23:21 UTC, jorgea-stripe approved these changes
LGTM!

2024-07-16 16:30 UTC, merged